### ISSUE TITLE
Probleme beim Auslesen 

### ISSUE THREAD

**Issue by pfeifferch** [tihmstar/shawazu-gb-dumper#1] opened 2024-09-19 15:35 UTC
Hallo tihmstar,

ich habe folgende Probleme und finde keine Lösung:

🤖
**Unter Android:**
 _• ohne Cardridge_
     
>   - Info.txt lesbar ✅

_•mit Cardridge_ 
 
>   - Laufwerk wird nicht angezeigt ❌

🪟
**Unter Windows:**
_• ohne Cardridge_ 
>   Die info.txt wird im Explorer angezeigt, bei dem Versuch sie im Editor zu öffnen kommt jedoch die Meldung "Info.txt kann nicht gefunden werden“ ❌

_•mit Cardridge_ 
>   - Spiele "Glücksrad" und "Mole Mania" ließen sich Kopieren, auf dem GPi/Recalbox jedoch nicht Spielen ✅❌
>  - SuperMarioLand-2 wird gar nicht erkannt ❌
>  - 6 andere Spiele werden angezeigt, bei dem Versuch die Dateien zu Kopieren kommt die Fehlermeldung "Das Element befindet sich nicht mehr in X:\ "

---

Hello tihmstar,

I have the following problems and can't find a solution:
🤖
**On Android:**

_• without Cardridge_

> - Info.txt readable ✅

_•with Cardridge_ 

> - No drive is displayed❌

🪟
**Under Windows:**
_• without cartridge_ 
> The info.txt is displayed in Explorer, but when i try to open it in the editor i get the message "Info.txt cannot be found" ❌

_•with cartridge_ 
> - Games "Wheel of Fortune" and "Mole Mania" could be copied, but not played on the GPi/Recalbox
> - SuperMarioLand-2 is not recognized at all ❌
> - 6 other games are displayed, when trying to copy the files the error message "The element is no longer in X:\ " appears

Update:

Nun mal am Raspberry Pi mit Recalbox angeschlossen. 
Ein paar Spiele getestet. 

Sie lassen sich Kopieren 
und öffnen. 
Es wird jedoch nur der Nintendo Startbildschirm angezeigt, danach passiert nichts mehr 

---
Now connected to Raspberry Pi with Recalbox. 
Tested a few games. 

They can be copied 
and opened. 
However, only the Nintendo start screen is displayed, after that nothing happens

**Comment by tihmstar** [comment] 2024-09-22 06:51
Hi,

i understand german, though, let's keep it english so that this can be helpful to others who run into a similar issue.
First of all, i suspect you're using a DIY kit, right?
In that case it sounds a lot like some of the pins aren't soldered correctly.

Pictures of front/back would be helpful to see where potentially there could be a faulty connection.

In general, i recommend using a multimeter to test continuity between front and back side of each solder joint (especially if you decided to solder the levelshifter directly to the PCB without the helper pins).
If you did the general hardware troubleshooting, you can continue to go for a more precise analysis of the issue.

Download the `shawazu-gb-dumper-hw_troubleshoot` build from https://github.com/tihmstar/shawazu-gb-dumper/releases.
This build (it's been a while, but as far as i remember) forces the Shawazu to shink a GB cartridge is connected (not-GBA).

First, you need to verify, that your 8 data pins are working correctly. btw, here is a nice pinout of the cartridge (https://there.oughta.be/assets/images/2021-12-16/pinout.jpg).

You connect the dumper without any cartridge and take a look at the `.gb` file in a hex viewer (for example `hexdump -C` on linux/mac). Since the pins are set to input, the high impedence should make them all eventually go to `1`. Thus, it is expected that the hexdump reads all `FF`.
If you see anything else, some pin must be shorted to ground or somthing.

The next step is to take a little wire or paperclip or sth, and connect one data pin to GND. best to do this directly on the cartridge connector. For example if you ground the LSB of the data bus, the `.gb` dump should read all `FE`.
Do this for each data pin individually and verify if the dump is correctly `FD`, `FB`, `F7`, etc...
Note: the Operating System reads the dump usually only once, then caches it and doesn't actually perform a re-read request. This read can happen at any time between when you connect your dumper, until the moment you actually open the file. So best is to short the pin to ground and hold it, then connect the dumper and copy the file to your PC. Only after the copy finished, you can stop shorting the pin. Then you need to disconnect the dumper from the PC and repeat the procedure for each pin.


Next, you need a GB cartridge (not GBA) to verify the address lines.
Insert the cartridge and copy the dump, then analyse it on your PC. This will be a bit more tricky, but i'll try my best to explain as good as i can.
For this step it is recommended, that you have a known good dump of the cartridge. Use a known-to-be-working dumper to create a good dump, or you know "ask a friend if they happen to have a dump" *wink wink*.
Usually the issue is, that one (or multiple) address bits are "stuck" i.e. tied to either 0 or 1 permanently.
When a read request is issued with a stuck address bit, the resulting dump is "folded" at that bit. When multiple bits are stuck, it can be "folded" multiple times.
The address bus is 16bit in size. When dumping the address space, you need to count up from 0x0000 to 0xFFFF.
Imagine counting: 
```
0x0000, 0x0001, 0x0002, 0x0003, 0x0004, 0x0005, 0x0006, 0x0007, 0x0008 
```
to get the first 8 bytes of the dump.
Let's assume (only) your LSB (0x0001) bit of the address bus is stuck, then the cartridge sees either of the following requests:
When the bit is stuck to 0:
```
0x0000, 0x0000, 0x0002, 0x0002, 0x0004, 0x0004, 0x0006, 0x0006, 0x0008 
```
When the bit is stuck to 1:
```
0x0001, 0x0001, 0x0003, 0x0003, 0x0005, 0x0005, 0x0007, 0x0007, 0x0009 
```

When you look at the hexdump, you will see that two consecutive bytes are always the same. For example if a good dump looks like this:
```
41 42 43 44 45 46 47 48
```
Your dump could look like this:
```
41 41 43 43 45 45 47 47
```
So if you see this pattern in the dump, you know your address is folded at the LSB (or address bit 0). Then you need to check that bit in the hardware and try to fix it.

Once you fixed that, keep looking for more repeating patterns.
For example let's assume you see this pattern:
```
41 42 43 44 41 42 43 44
```
Here the data repeats every 4 byte. 4 in binary is 0b0100, that means address bit A3 is stuck.
So the cartridge could see requests like this:
```
0x0000, 0x0001, 0x0002, 0x0003, 0x0000, 0x0001, 0x0002, 0x0003, 0x0008, 0x0009, 0x000a, 0x000b, 0x0008
```

Following this procedure should help you check most of the pins, which usually resolves the decribed problem.
There are a couple special pins like CLK, ~WR, ~RD, ~CS, ~RST which i glossed over.
But for the sake of completeness let's handle them too:
- ~RST is not really used on GB cartridges. Don't remember about GBA, but here another method will be needed.
- CLK is really only use by gameboy camera, you can ignore that unless you're actually dealing with GB camera
- if ~CS doesn't work, no control signals will ever reach the chip
- ~RD is "clocked" for reading. since you see something happening, this likely works finr
- ~WR is used for back switching and writing to savegame.


If you need more assistance, i'm hanging around in [Corco Cartridge Dev](https://discord.com/invite/jxGfqw2mdt) server in the SHAWAZU subsection.

**Comment by pfeifferch** [comment] 2024-09-22 11:38
Hello 

Thank you for the comprehensive answer.

Correct, it is the DIY set. 

I think it will take me a few days to get this done.

I have already installed the dumper firmware, but strangely enough it says that no cartridge is installed. 
Do you have any idea what the problem is and what I can do here? Otherwise it will be difficult with the hex editor.


By the way, my English is so bad that I have to use Google Translate 😉😰



![Screenshot_2024-09-22-13-15-54-995_com cxinventor file explorer](https://github.com/user-attachments/assets/91eefe42-36dd-4b97-acc1-69073d05576c)

![IMG_20240922_133557](https://github.com/user-attachments/assets/f6ccedd5-0769-4acd-8ec5-c9d2f3c50be2)
![IMG_20240922_133548](https://github.com/user-attachments/assets/3e588fc7-73b5-4268-b76f-2b865722d616)
![IMG_20240922_133519](https://github.com/user-attachments/assets/5149bb3b-5766-4451-bbde-a59097daffda)
![IMG_20240922_133507](https://github.com/user-attachments/assets/67bad416-fd71-4300-bd04-54c9cc006140)
![IMG_20240922_133429](https://github.com/user-attachments/assets/38183ae6-0d83-401f-8b6e-cb3c408489a9)
![IMG_20240922_133415](https://github.com/user-attachments/assets/fcb4047d-b703-479b-aef8-c29d8836471d)


Edited : 
Is chip select only necessary if the cartridge is to be written to (games) or does it also have to be connected for reading? (on RR reads as if it is not necessary for the reading process)


Update 2: 
The UF2 for the normal firmware and the troubleshooting have the same MD5. 
It seems that the normal firmware file ended up in the TS archive.
MD5: a0db9702746ae011eb804d629ac33a9b

Update 3:
The troubleshooting under version 1.2.5 is running. So it seems that the wrong file is in 1.2.7. I'll start it this afternoon

**Comment by tihmstar** [comment] 2024-09-23 12:10
Soldering looks mostly good, will check the debug firmware later...

One thing i did notice is that it looks like you might have forgotten to solder the D7 pin on the back of the board. 
Check the tutorial at 3:45 https://youtu.be/dES8QW8xg44?t=225&feature=shared

**Comment by pfeifferch** [comment] 2024-09-23 19:47
Hello 

I removed the soldering at the test point.


---

I ordered a second set and wanted to start again from the beginning. Unfortunately, the problems started under Windows after flashing. 
The info.txt cannot be opened. 
![IMG_20240923_214131](https://github.com/user-attachments/assets/6aca3165-9abf-4a0b-a590-f5bd5acf108c)

**Comment by tihmstar** [comment] 2024-09-27 06:15
Why did you remove the soldering at the test point?

**Comment by Jigsaw0815** [comment] 2024-10-30 20:34
![IMG_0744](https://github.com/user-attachments/assets/d4b2b577-7211-4687-8e1c-7ec4aa6d6e8c)



![IMG_0743](https://github.com/user-attachments/assets/061b6f63-b0ab-4b9c-a54d-69fc9b72e07f)
Hello have Problems too. It Show no Game inside i test the Hardware Test files. That works

**Comment by tihmstar** [comment] 2024-11-10 09:11
@Jigsaw0815 your soldering looks really good. I think for "general troubleshooting" i suggest to join the discord [Corco Cartridge Dev](https://discord.com/invite/jxGfqw2mdt) server in the SHAWAZU subsection.

I get that sometimes it doesn't just work out of the box (which is fine), but that is super hard to debug here. In the discord people can help each other much better.

Closing this issue for now.
For future reference: If there is some very specific thing, open issue. For general troubleshooting come and join discord

**Closed as completed by tihmstar** 2024-11-10 09:11 UTC
